{% set name = "spectra" %}
{% set version = "0.8.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/spectra.git
    git_tag: master
requirements:
    build:
      - git
      - make
      - pin_compatible('cmake', 'min_pin='x.x', max_pin='x')
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - llvm-openmp               # [osx]
      - pin_compatible('eigen', 'min_pin='x.x.x', 'max_pin='x.x')
test:
  commands:
    - test -f ${PREFIX}/include/Spectra/GenEigsBase.h
about:
    home: https://github.com/GQCG/spectra
    license: Mozilla Public License 2.0 (MPL 2.0)
    license_file: LICENSE
    summary: 'A header-only C++ library for large scale eigenvalue problems.'
